[app]
id="pixiv-swift"
name="Pixiv-Swift"
description="一个基于 SwiftUI 的 Pixiv 第三方客户端"
authors=["Eslzzyl"]
ai-assisted=true
repo="Eslzzyl/Pixiv-SwiftUI"
filename="Pixiv-SwiftUI.ipa"

[icon]
light="light.png"
dark="dark.png"