[app]
id="lanlu"
name="lanlu-iOS"
description="lanlu client for iOS"
authors=["copurx", "DeeChael"]
ai-assisted=true
repo="DeeChael/lanlu-iOS"
filename="lanlu-iOS.ipa"

[icon]
light="light.png"
dark="dark.png"